version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_in_jenkins
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test_user -d test_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jenkins:
    build: .
    container_name: jenkins
    user: root
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ../jenkins_shared:/shared

volumes:
  postgres_data:
  jenkins_home:

